    "th07 Stats ReimuA": "Hakurei Reimu (Spirit)",
    "th07 Stats ReimuB": "Hakurei Reimu (Dream)",
    "th07 Stats MarisaA": "Kirisame Marisa (Magic)",
    "th07 Stats MarisaB": "Kirisame Marisa (Love)",
    "th07 Stats SakuyaA": "Izayoi Sakuya (Illusion)",
    "th07 Stats SakuyaB": "Izayoi Sakuya (Time)",
    "th08 Stats Reimu": "Hakurei Reimu",
    "th08 Stats Yukari": "Yakumo Yukari",
    "th08 Stats Marisa": "Kirisame Marisa",
    "th08 Stats Sakuya": "Izayoi Sakuya",
    "th08 Stats Youmu": "Konpaku Youmu",
    "th08 Stats Yuyuko": "Saigyouji Yuyuko",
    "th07 Stats Play Count": "<tl$Play Count\t$Hakurei Reimu (Spirit)\t $Hakurei Reimu (Dream)\t $Kirisame Marisa (Magic)\t $Kirisame Marisa (Love)\t $Izayoi Sakuya (Illusion)\t $Izayoi Sakuya (Time)\t> Easy\t Norm\t Hard\t Luna\t Extra\t Total",
    "th07 Stats Clear Count +Phantasm": "<tl$Clear Count\t$Hakurei Reimu (Spirit)\t $Hakurei Reimu (Dream)\t $Kirisame Marisa (Magic)\t $Kirisame Marisa (Love)\t $Izayoi Sakuya (Illusion)\t $Izayoi Sakuya (Time)\t> %6d\t %6d\t %6d\t %6d\t %6d\t %6d\t %6d",
    "th06 Stats ReimuA": "Hakurei Reimu (Spirit)",
    "th06 Stats ReimuB": "Hakurei Reimu (Dream)",
    "th06 Stats MarisaA": "Kirisame Marisa (Magic)",
    "th06 Stats MarisaB": "Kirisame Marisa (Love)"
